# Generated by Django 6.0.2 on 2026-03-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
